#!/bin/bash -e

# Do internal repository package management
pushd dev > /dev/null
./update-repository-packages-tc
popd > /dev/null


#Install casperjs to target
if [ ! -d dev/casperjs ]; then
    git clone git://github.com/n1k0/casperjs.git dev/casperjs
    cd dev/casperjs
    git checkout tags/1.0.2
    cd ../..
fi
export PATH=$PATH:$(pwd)/dev/casperjs/bin
export PATH=$PATH:$(pwd)/node_modules/phantomjs/bin


# Build configuration
BUILD_PARAMS=""
if [ -n "$BUILD_NUMBER" ]; then
  BUILD_PARAMS="${BUILD_PARAMS} -Dbuild.number=\"$BUILD_NUMBER\""
fi 
if [ -n "$BUILD_VCS_NUMBER" ]; then
  BUILD_PARAMS="${BUILD_PARAMS} -Dbuild.vcs.number=\"$BUILD_VCS_NUMBER\""
fi 


# Ivy configuration
echo "setting ivy cache dir"
IVY_PARAMS="-Dsbt.ivy.home=.ivy -Divy.home=.ivy"
echo $IVY_PARAMS

# Do not set a proxy for gc2.dc1.gnm
PROXY_CONF=""
if [ "$(hostname -d)" != "gc2.dc1.gnm" ]
then
    # Proxy for Play
    export proxy_host=devproxy.gul3.gnl
    export proxy_port=3128

    # Proxy for SBT
    PROXY_CONF="-Dhttp.proxyHost=devproxy.gul3.gnl -Dhttp.proxyPort=3128"
fi


# MaxPermSize specifies the the maximum size for the permanent generation heap,
# a heap that holds objects such as classes and methods. Xmx is the heap size.
JVM_ARGS="-Xmx4096M -XX:MaxPermSize=2048m -XX:ReservedCodeCacheSize=128m"

cat /dev/null | java $JVM_ARGS \
  -Dsbt.log.noformat=true \
  -DAPP_SECRET="myKV8HQkjcaxygbDuyneHBeyFgsyyM8yCFFOxyDoT0QGuyrY7IyammSyP1VivCxS" \
  $PROXY_CONF \
  $BUILD_PARAMS \
  $IVY_PARAMS \
  -jar `dirname $0`/dev/sbt-launch-0.12.2.jar "$@"
