#!/bin/bash -e

# Do internal repository package management
pushd dev > /dev/null
./update-repository-packages
popd > /dev/null


#Install casperjs to target
if [ ! -d dev/casperjs ]; then
    git clone git://github.com/n1k0/casperjs.git dev/casperjs
    cd dev/casperjs
    git checkout tags/1.0.2
    cd ../..
fi
export PATH=$PATH:$(pwd)/dev/casperjs/bin
export PATH=$PATH:$(pwd)/node_modules/phantomjs/bin


# Build configuration
BUILD_PARAMS=""
if [ -n "$BUILD_NUMBER" ]; then
  BUILD_PARAMS="${BUILD_PARAMS} -Dbuild.number=\"$BUILD_NUMBER\""
fi 
if [ -n "$BUILD_VCS_NUMBER" ]; then
  BUILD_PARAMS="${BUILD_PARAMS} -Dbuild.vcs.number=\"$BUILD_VCS_NUMBER\""
fi 


# Ivy configuration params and debug option
IVY_PARAMS=""
DEBUG_PARAMS=""
for arg in "$@"
do
    if [ "$arg" == "--directory-ivy-cache" ]; then
      echo "setting ivy cache dir"
      IVY_PARAMS="-Dsbt.ivy.home=.ivy -Divy.home=.ivy"
      shift
    fi

    if [ "$arg" == "--debug" ]; then
      echo "setting java process as debuggable"
      DEBUG_PARAMS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=1044"
      shift
    fi
done


# Grunt configuration
export GRUNT_ISDEV=1


# MaxPermSize specifies the the maximum size for the permanent generation heap,
# a heap that holds objects such as classes and methods. Xmx is the heap size.
JVM_ARGS="-Xmx4096M -XX:MaxPermSize=2048m -XX:ReservedCodeCacheSize=128m"

java $JVM_ARGS \
  -Djava.awt.headless=true \
  -DAPP_SECRET="myKV8HQkjcaxygbDuyneHBeyFgsyyM8yCFFOxyDoT0QGuyrY7IyammSyP1VivCxS" \
  $BUILD_PARAMS \
  $IVY_PARAMS \
  $DEBUG_PARAMS \
  -jar `dirname $0`/dev/sbt-launch-0.12.2.jar "$@"
